### ISSUE TITLE
How to add clock-panel to my dev env

### ISSUE THREAD

**Issue by yuvaraj951** [grafana/clock-panel#15]
please tell me how to add clock-panel to my grafana dev env...please help me out..

**Comment by daniellee** [comment]
Do you just want to install it or do you want to change the code?

If you want to change it, here are some instructions for getting started with developing plugins: 

http://grafana.org/blog/2016/04/08/clock-plugin-p1.html

Couple of steps:
1. Fork this project (if you are going to send a PR later)
2. Git clone into your grafana plugins directory
3. Restart the grafana server

Otherwise, you can install it with the cli. Instructions for bash command line (not sure what OS you are on) that are run from the grafana directory:

```
./bin/grafana-cli --pluginsDir "./data/plugins" plugins install grafana-clock-panel
```

You might need sudo, depending on where your plugins directory is located.
