### ISSUE TITLE
Bug: New Query Option affecting existing dashboards

### ISSUE THREAD

**Issue by briangann** [grafana/clock-panel#186]
We'll need a migration or detection of the query, existing dashboards using clock are showing an error (Invalid Measurement)

![image](https://github.com/grafana/clock-panel/assets/7364245/e72a6561-d1bc-42e3-a8c6-83cd79a91ca3)

**Comment by tolzhabayev** [comment]
@academo I guess we should write a migration now

**Comment by academo** [comment]
This issue is a result of the panel now accommodating queries, rather than a complete error. The error displayed in the panel is not from the clock panel, but from InfluxDB, which returns "invalid measurement" when an invalid query is submitted to an influxdb endpoint.

The clock panel previously didn't require a datasource to display data, but now it does to some extent. Consequently, Grafana is executing an empty query in the default datasource, causing an error. If your default datasource was, for instance, test datasource, this error wouldn't occur.

Currently, there's no direct solution to this error. Grafana doesn't support panels programmatically indicating that they need a query. The only suggestion is in the plugin.json, which was previously used by the clock panel.

As a workaround, simply select "Grafana" as a datasource or "test datasource" if available.

@tolzhabayev @briangann I am inclined to tag this a "wont fix/cant fix" and pointing any possible report of this error to this message.

**Comment by briangann** [comment]
fixed by #192
