### ISSUE TITLE
Adding clock panel and getting error 

### ISSUE THREAD

**Issue by mmaberry-yottaa** [grafana/clock-panel#23]
Using  Grafana v3.1.1 (commit: a4d2708)  and clock v0.0.9 when I try to add a clock panel I am receiving the following error: _.defaultsDeep is not a function. Any assistance would be appreciated.

**Comment by Wicaeed** [comment]
This is also an issue on brand new pulls of grafana 3.1.1 via docker and installing the clock-panel plugin

**Comment by daniellee** [comment]
Sorry, no support for older versions of Grafana - maybe it's time to upgrade to v4.2.0 :smiley: 

The error is due to the Lodash library being upgraded in Grafana 4.0 which allowed the fixing of this bug: #20. Try using an older version of the plugin than 0.0.9 if you do not want to upgrade your Grafana.
