### ISSUE TITLE
Background color gets lost when clock displayed on dashboard

### ISSUE THREAD

**Issue by jrbeilke** [grafana/clock-panel#5]
Have a countdown clock on one of our dashboards with a custom background color (red), but when switching back and forth between dashboards or refreshing a dashboard the background color is lost. When I first set the background color it works as expected, but then when I come back to the dashboard the panel does not display the custom color (editing the panel does show the color is still selected).

Used the Grafana CLI to install the plugin, and the package.json shows version 1.0.0 in grafana-clock-panel.

**Comment by daniellee** [comment]
Confirmed. Thanks for the report.

**Comment by daniellee** [comment]
Fixed by this [commit](https://github.com/grafana/clock-panel/commit/c78abfd6772d2837878a64fdfbf5d8db0cae4280) and a new version, 0.0.7 released. 

This fix depends on a change to Grafana which will be released with the new beta so it won't work straight away. I had another fix that would work right now but using the new *panel-initialized* event (thanks @torkelo for adding it!) is much cleaner.
